[package]
name = "rusty_toolbox"
version = "1.1.1"
authors = ["meidhy demagny <meidhy.demagny@gmail.com>"]

[dependencies]
failure = ""
walkdir = ""
regex = ""
rayon = ""
chrono = { version = "", features = ["serde", "rustc-serialize"] }
durationfmt = ""
quickersort = ""
lazy_static = ""